### ISSUE TITLE
Reference to CP/M / Add a cover

### ISSUE THREAD

**Issue by mbernardi1961** [oldpatientsea/agon-bbc-basic-manual#24]
While the generic version of BBC Basic (Z80) was written for CP/M, the version for the AgonLight, has been enhanced, so any sections referring to CP/M should be removed or revised.
Also a cover image would be nice.

**Comment by oldpatientsea** [comment]
Nice idea. Thank you.

Sorry but I no longer have time to maintain this and am archiving the repository. Please feel free to fork and make any adjustments there.
